COMP: Fix configuration of source files when project added as a subdirectory
This commit ensures source files are configured in the expected
sub-directory when project is added using "add_subdirectory" command.

It fixes error like the following:

  ..\..\..\draco\src\draco/compression/decode.h(18):
  fatal error C1083: Cannot open include file: 'draco/draco_features.h': No such file or directory